FROM 047590332772.dkr.ecr.eu-central-1.amazonaws.com/nodejs:16

WORKDIR /usr/src/app

ARG PORT
ENV PORT=$PORT
ARG GITHUB_TOKEN
ENV GITHUB_TOKEN=$GITHUB_TOKEN
ARG API_HOST
ENV API_HOST=$API_HOST
ARG REGION
ENV REGION=$REGION
ARG SECRET_ID
ENV SECRET_ID=$SECRET_ID
ARG USER_SDK_URL
ENV USER_SDK_URL=$USER_SDK_URL
ARG S3_BUCKET
ENV S3_BUCKET=$S3_BUCKET
ARG PARTSLINK_ACCOUNT_LIMIT
ENV PARTSLINK_ACCOUNT_LIMIT=$PARTSLINK_ACCOUNT_LIMIT
ARG PARTSLINK_S3_FOLDER
ENV PARTSLINK_S3_FOLDER=$PARTSLINK_S3_FOLDER
ARG CARFAX_S3_FOLDER
ENV CARFAX_S3_FOLDER=$CARFAX_S3_FOLDER
ARG PARTSLINK_SETTINGS
ENV PARTSLINK_SETTINGS=$PARTSLINK_SETTINGS
ARG CARFAX_SETTINGS
ENV CARFAX_SETTINGS=$CARFAX_SETTINGS

COPY package*.json ./
COPY .npmrc ./

RUN npm install

COPY . .

RUN npm run build

EXPOSE $PORT

RUN apt-get update
RUN apt-get install -y gconf-service libasound2 libatk1.0-0 libcairo2 libcups2 libfontconfig1 libgdk-pixbuf2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libxss1 fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils
RUN apt-get install chromium -y

CMD [ "npm", "start" ]
